---
- hosts: mymachine
  remote_user: root
  become: true
  connection: ssh
  vars_files:
    - ansible/vars/default.yml
  tasks:
    - name: spring-boot-hello-world
      docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_container_image }}"
        state: started
        pull: true
        cpu_period: "{{ container_cpu_period }}"
        memory: "{{ container_memory }}"
        ports: "{{ container_port }}:8080"
      with_sequence: count={{ create_containers }}
